export const PAGE_BACKEND_CANISTER_ID = process.env.PAGE_BACKEND_CANISTER_ID;
export const WIKI_BACKEND_CANISTER_ID = process.env.WIKI_BACKEND_CANISTER_ID;
export const WIKI_FRONTEND_CANISTER_ID = process.env.WIKI_FRONTEND_CANISTER_ID;
export const INTERNET_IDENTITY_CANISTER_ID = process.env.INTERNET_IDENTITY_CANISTER_ID;
